Fixed a critical logic error again

diff --git a/csfru b/csfru
--- a/csfru
+++ b/csfru
@@ -4,13 +4,19 @@ do
     case "${option}"
     in
     a) APIKEY="${OPTARG}";;
-    i) ALBUMDIR=$(realpath "${OPTARG}"); SPECTROGRAMSDIR="$ALBUMDIR/Spectrograms";;
-    o) BASESPECTROGRAMSDIR=$(realpath "${OPTARG}") ||
+    i) ALBUMDIR=$(realpath -e "${OPTARG}") ||
+    echo "-i error"
+    echo "Please specify a directory that exists!"
+    echo "Specified directory: "
+    echo "$ALBUMDIR"
+    exit; 
+    SPECTROGRAMSDIR="$ALBUMDIR/Spectrograms";;
+    o) BASESPECTROGRAMSDIR=$(realpath -e "${OPTARG}") ||
     echo "-o error"
     echo "Please specify a directory that exists!"
     echo "Specified directory: "
     echo "$BASESPECTROGRAMSDIR"
-    exit
+    exit;
     SPECTROGRAMSDIR=$(realpath "${OPTARG}/${ALBUMDIR##*/}")
     ;;
     s) SMALL="true";;
@@ -32,15 +38,6 @@ if [ ! "$ALBUMDIR" ]
 then
     echo "${0##*/}: has exited because an input directory was not specified"
     exit
-
-elif [ ! -d "$ALBUMDIR" ]
-then
-    echo "-i error"
-    echo "Please specify a directory that exists!"
-    echo "Specified directory: "
-    echo "$ALBUMDIR"
-    exit
-fi
 
 mkdir -p "$SPECTROGRAMSDIR"
 for SONG in "$ALBUMDIR"/*.flac;
